sudo: required

matrix:
  include:
    - os: linux
      language: dart
    - os: windows
      language: minimal

env:
  - EVM_EMACS=emacs-26.1-travis

before_install:

  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask --verbose

script:
  - make

notifications:
  email: false
